spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Prakhar-FF13/polarbookshop-config-repo"
          timeout: 5
          clone-on-start: true
          force-pull: true
          default-label: "main"

server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      min-spare: 5
      max: 50
